spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: email_service
          uri: http://localhost:8083
          predicates:
            - Path=/email/**
        - id: order_service
          uri: http://localhost:8085
          predicates:
            - Path=/order/**
        - id: product_service
          uri: http://localhost:8087
          predicates:
            - Path=/product/**
        - id: stock_service
          uri: http://localhost:8081
          predicates:
            - Path=/stock/**
        - id: eureka-server
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/main
        - id: zipkin-server
          uri: http://localhost:9411
          predicates:
            - Path=/eureka/main
          filters:
            - SetPath=/

server:
  port: 8089

logging:
  level:
    root: info
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: INFO
    org.springframework.cloud.gateway: TRACE

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true

management:
  tracing:
    sampling:
      probability: 1.0
